import Foundation
import VPNCore

/// Localized long descriptions for DNS presets (all 18 app languages —
/// no English fallback anywhere: every language carries every string).
/// Keyed by preset id; missing key = programming error, caught by tests.
extension AppCopy {
    func presetDescription(_ preset: DNSPreset) -> String {
        let table = Self.presetDescriptions[language] ?? Self.presetDescriptions[.english]!
        return table[preset.id] ?? Self.presetDescriptions[.english]![preset.id]!
    }

    func presetFilterBadge(_ preset: DNSPreset) -> String {
        switch preset.filter {
        case .none: return text(.dnsFilterNone)
        case .malware: return text(.dnsFilterMalware)
        case .ads: return text(.dnsFilterAds)
        case .family: return text(.dnsFilterFamily)
        }
    }

    /// preset id -> localized description, per language.
    static let presetDescriptions: [AppLanguage: [String: String]] = [
        .english: [
            "cloudflare": "The fastest public resolver. No content filtering; query logs deleted after 24h.",
            "google": "Google's global anycast. No content filtering, standard Google privacy policy.",
            "adguard-unfiltered": "AdGuard's plain resolver: no blocking at all, privacy-first, no DNS logs.",
            "yandex": "Fastest in Russia/CIS region. No filtering.",
            "dns-watch": "German, privacy-friendly, no filtering, no logs.",
            "verisign": "Stable US infrastructure. No filtering.",
            "level3": "Classic veteran resolver. No filtering.",
            "quad9": "Blocks malware, phishing and botnet command domains. Swiss non-profit; no IP logging.",
            "cloudflare-malware": "Cloudflare speed plus a blocklist of malware and phishing domains.",
            "dns0-zero": "EU non-profit. Blocks malware and phishing domains.",
            "opendns": "Cisco's resolver. Blocks phishing and identity-theft sites.",
            "comodo": "Blocks malicious and phishing domains.",
            "adguard": "Blocks ads, trackers, analytics beacons and malware domains. Some sites may break (anti-adblock walls).",
            "cloudflare-family": "Blocks adult (18+) content and malware domains.",
            "adguard-family": "Blocks adult content, ads, trackers and malware; enforces safe search in engines.",
            "cleanbrowsing-family": "Strict mode: blocks adult content, malware and phishing; forces safe search on Google/Bing/Yandex.",
            "cleanbrowsing-adult": "Blocks only adult (18+) sites; everything else is allowed.",
            "opendns-familyshield": "Preconfigured: blocks adult content and phishing. Nothing to set up.",
            "yandex-family": "Blocks adult content and suggestive pages; Russian infrastructure.",
        ],
        .russian: [
            "cloudflare": "Самый быстрый публичный резолвер. Без фильтрации; логи запросов удаляются через 24 часа.",
            "google": "Глобальный anycast от Google. Без фильтрации контента, стандартная политика конфиденциальности Google.",
            "adguard-unfiltered": "Обычный резолвер AdGuard: никаких блокировок, приватность, логи DNS не ведутся.",
            "yandex": "Самый быстрый в России и СНГ. Без фильтрации.",
            "dns-watch": "Немецкий, дружелюбный к приватности, без фильтров и логов.",
            "verisign": "Стабильная инфраструктура США. Без фильтрации.",
            "level3": "Классический ветеран среди резолверов. Без фильтрации.",
            "quad9": "Блокирует вредоносные, фишинговые домены и управляющие центры ботнетов. Швейцарский некоммерческий сервис; IP не логируются.",
            "cloudflare-malware": "Скорость Cloudflare плюс блок-лист вредоносных и фишинговых доменов.",
            "dns0-zero": "Европейский некоммерческий сервис. Блокирует вирусные и фишинговые домены.",
            "opendns": "Резолвер Cisco. Блокирует фишинг и сайты для кражи личных данных.",
            "comodo": "Блокирует вредоносные и фишинговые домены.",
            "adguard": "Блокирует рекламу, трекеры, аналитические маячки и вредоносные домены. Некоторые сайты могут работать некорректно (анти-адблок).",
            "cloudflare-family": "Блокирует контент 18+ и вредоносные домены.",
            "adguard-family": "Блокирует контент 18+, рекламу, трекеры и вирусы; принудительно включает безопасный поиск.",
            "cleanbrowsing-family": "Строгий режим: блокирует контент 18+, вирусы и фишинг; принудительный безопасный поиск в Google/Bing/Яндексе.",
            "cleanbrowsing-adult": "Блокирует только сайты 18+; всё остальное — без ограничений.",
            "opendns-familyshield": "Готовая настройка: блокирует контент 18+ и фишинг. Ничего настраивать не нужно.",
            "yandex-family": "Блокирует контент 18+ и «сомнительные» страницы; инфраструктура Яндекса.",
        ],
        .spanish: [
            "cloudflare": "El resolutor público más rápido. Sin filtrado de contenido; registros borrados a las 24h.",
            "google": "Anycast global de Google. Sin filtrado de contenido, política de privacidad estándar de Google.",
            "adguard-unfiltered": "Resolutor básico de AdGuard: sin bloqueos, privacidad ante todo, sin registros DNS.",
            "yandex": "El más rápido en Rusia/CEI. Sin filtrado.",
            "dns-watch": "Alemán, orientado a la privacidad, sin filtros ni registros.",
            "verisign": "Infraestructura estable de EE. UU. Sin filtrado.",
            "level3": "Resolutor clásico y veterano. Sin filtrado.",
            "quad9": "Bloquea malware, phishing y dominios de control de botnets. Sin ánimo de lucro suizo; sin registro de IP.",
            "cloudflare-malware": "La velocidad de Cloudflare más una lista de bloqueo de malware y phishing.",
            "dns0-zero": "Organización europea sin ánimo de lucro. Bloquea malware y phishing.",
            "opendns": "Resolutor de Cisco. Bloquea phishing y robo de identidad.",
            "comodo": "Bloquea dominios maliciosos y de phishing.",
            "adguard": "Bloquea anuncios, rastreadores, analíticas y malware. Algunos sitios pueden fallar (muros anti-adblock).",
            "cloudflare-family": "Bloquea contenido para adultos (+18) y malware.",
            "adguard-family": "Bloquea contenido para adultos, anuncios, rastreadores y malware; activa la búsqueda segura.",
            "cleanbrowsing-family": "Modo estricto: bloquea contenido adulto, malware y phishing; búsqueda segura en Google/Bing/Yandex.",
            "cleanbrowsing-adult": "Bloquea solo sitios para adultos (+18); todo lo demás está permitido.",
            "opendns-familyshield": "Preconfigurado: bloquea contenido adulto y phishing. Nada que ajustar.",
            "yandex-family": "Bloquea contenido adulto y páginas sugerentes; infraestructura rusa.",
        ],
        .german: [
            "cloudflare": "Der schnellste öffentliche Resolver. Keine Inhaltsfilterung; Abfrageprotokolle werden nach 24h gelöscht.",
            "google": "Globales Anycast von Google. Keine Inhaltsfilterung, standardmäßige Google-Datenschutzrichtlinie.",
            "adguard-unfiltered": "AdGuards schlichter Resolver: keinerlei Blockierung, Datenschutz vor allem, keine DNS-Protokolle.",
            "yandex": "Am schnellsten in Russland/GUS. Keine Filterung.",
            "dns-watch": "Deutschland, datenschutzfreundlich, ohne Filter und Protokolle.",
            "verisign": "Stabile US-Infrastruktur. Keine Filterung.",
            "level3": "Klassischer Veteran unter den Resolvern. Keine Filterung.",
            "quad9": "Blockiert Malware, Phishing und Botnet-Kontrolldomänen. Schweizer Non-Profit; keine IP-Protokollierung.",
            "cloudflare-malware": "Cloudflare-Geschwindigkeit plus Sperrliste für Malware- und Phishing-Domänen.",
            "dns0-zero": "EU-Non-Profit. Blockiert Malware- und Phishing-Domänen.",
            "opendns": "Resolver von Cisco. Blockiert Phishing und Identitätsdiebstahl.",
            "comodo": "Blockiert bösartige Domänen und Phishing.",
            "adguard": "Blockiert Werbung, Tracker, Analyse-Pixel und Malware. Manche Sites können Probleme machen (Anti-Adblock).",
            "cloudflare-family": "Blockiert Inhalte für Erwachsene (18+) und Malware.",
            "adguard-family": "Blockiert Erwachseneninhalte, Werbung, Tracker und Malware; erzwingt sichere Suche.",
            "cleanbrowsing-family": "Strenger Modus: blockiert Erwachseneninhalte, Malware und Phishing; sichere Suche bei Google/Bing/Yandex.",
            "cleanbrowsing-adult": "Blockiert nur Erwachsenenseiten (18+); alles andere ist erlaubt.",
            "opendns-familyshield": "Vorkonfiguriert: blockiert Erwachseneninhalte und Phishing. Kein Einrichten nötig.",
            "yandex-family": "Blockiert Erwachseneninhalte und anstößige Seiten; russische Infrastruktur.",
        ],
        .french: [
            "cloudflare": "Le résolveur public le plus rapide. Aucun filtrage ; journaux supprimés après 24h.",
            "google": "Anycast mondial de Google. Aucun filtrage de contenu, politique de confidentialité Google standard.",
            "adguard-unfiltered": "Résolveur simple d'AdGuard : aucun blocage, confidentialité d'abord, aucun journal DNS.",
            "yandex": "Le plus rapide en Russite/CEI. Aucun filtrage.",
            "dns-watch": "Allemand, respectueux de la vie privée, sans filtre ni journal.",
            "verisign": "Infrastructure américaine stable. Aucun filtrage.",
            "level3": "Résolveur vétéran classique. Aucun filtrage.",
            "quad9": "Bloque les logiciels malveillants, le phishing et les domaines de contrôle de botnets. À but non lucratif suisse ; aucune journalisation d'IP.",
            "cloudflare-malware": "La vitesse de Cloudflare plus une liste de blocage malware et phishing.",
            "dns0-zero": "Organisation à but non lucratif de l'UE. Bloque les domaines malveillants et le phishing.",
            "opendns": "Résolveur de Cisco. Bloque le phishing et le vol d'identité.",
            "comodo": "Bloque les domaines malveillants et le phishing.",
            "adguard": "Bloque publicités, traqueurs, balises d'analyse et malwares. Certains sites peuvent dysfonctionner (anti-adblock).",
            "cloudflare-family": "Bloque les contenus pour adultes (18+) et les malwares.",
            "adguard-family": "Bloque contenus adultes, publicités, traqueurs et malwares ; force la recherche sécurisée.",
            "cleanbrowsing-family": "Mode strict : bloque contenus adultes, malwares et phishing ; recherche sûre sur Google/Bing/Yandex.",
            "cleanbrowsing-adult": "Bloque uniquement les sites adultes (18+) ; tout le reste est autorisé.",
            "opendns-familyshield": "Préconfiguré : bloque contenus adultes et phishing. Rien à régler.",
            "yandex-family": "Bloque contenus adultes et pages suggestives ; infrastructure russe.",
        ],
        .italian: [
            "cloudflare": "Il resolver pubblico più veloce. Nessun filtraggio contenuti; log cancellati dopo 24h.",
            "google": "Anycast globale di Google. Nessun filtraggio, normale informativa sulla privacy Google.",
            "adguard-unfiltered": "Resolver semplice di AdGuard: nessun blocco, privacy prima di tutto, nessun log DNS.",
            "yandex": "Il più veloce in Russia/CIS. Nessun filtraggio.",
            "dns-watch": "Tedesco, attento alla privacy, senza filtri né log.",
            "verisign": "Infrastruttura USA stabile. Nessun filtraggio.",
            "level3": "Resolver storico e classico. Nessun filtraggio.",
            "quad9": "Blocca malware, phishing e domini di controllo dei botnet. Non-profit svizzera; nessun log degli IP.",
            "cloudflare-malware": "Velocità Cloudflare più blocklist di domini malware e phishing.",
            "dns0-zero": "Non-profit europea. Blocca domini malware e phishing.",
            "opendns": "Resolver di Cisco. Blocca phishing e furto d'identità.",
            "comodo": "Blocca domini dannosi e di phishing.",
            "adguard": "Blocca pubblicità, tracker, beacon analitici e malware. Alcuni siti potrebbero non funzionare (anti-adblock).",
            "cloudflare-family": "Blocca contenuti per adulti (18+) e domini malware.",
            "adguard-family": "Blocca contenuti per adulti, pubblicità, tracker e malware; impone la ricerca sicura.",
            "cleanbrowsing-family": "Modalità severa: blocca contenuti adulti, malware e phishing; ricerca sicura su Google/Bing/Yandex.",
            "cleanbrowsing-adult": "Blocca solo i siti per adulti (18+); tutto il resto è consentito.",
            "opendns-familyshield": "Preconfigurato: blocca contenuti per adulti e phishing. Nulla da impostare.",
            "yandex-family": "Blocca contenuti per adulti e pagine discutibili; infrastruttura russa.",
        ],
        .portuguese: [
            "cloudflare": "O resolvedor público mais rápido. Sem filtragem de conteúdo; registros apagados após 24h.",
            "google": "Anycast global do Google. Sem filtragem de conteúdo, política de privacidade padrão do Google.",
            "adguard-unfiltered": "Resolvedor simples da AdGuard: sem bloqueios, privacidade em primeiro lugar, sem registros de DNS.",
            "yandex": "O mais rápido na Rússia/CIS. Sem filtragem.",
            "dns-watch": "Alemão, focado em privacidade, sem filtros nem registros.",
            "verisign": "Infraestrutura estável dos EUA. Sem filtragem.",
            "level3": "Resolvedor clássico e veterano. Sem filtragem.",
            "quad9": "Bloqueia malware, phishing e domínios de comando de botnets. Sem fins lucrativos suíço; sem registro de IPs.",
            "cloudflare-malware": "Velocidade da Cloudflare mais lista de bloqueio de domínios de malware e phishing.",
            "dns0-zero": "Organização europeia sem fins lucrativos. Bloqueia domínios de malware e phishing.",
            "opendns": "Resolvedor da Cisco. Bloqueia phishing e roubo de identidade.",
            "comodo": "Bloqueia domínios maliciosos e de phishing.",
            "adguard": "Bloqueia anúncios, rastreadores, análises e malware. Alguns sites podem falhar (bloqueio anti-adblock).",
            "cloudflare-family": "Bloqueia conteúdo adulto (18+) e domínios de malware.",
            "adguard-family": "Bloqueia conteúdo adulto, anúncios, rastreadores e malware; força a busca segura.",
            "cleanbrowsing-family": "Modo estrito: bloqueia conteúdo adulto, malware e phishing; busca segura no Google/Bing/Yandex.",
            "cleanbrowsing-adult": "Bloqueia apenas sites adultos (18+); todo o resto é permitido.",
            "opendns-familyshield": "Pré-configurado: bloqueia conteúdo adulto e phishing. Nada para configurar.",
            "yandex-family": "Bloqueia conteúdo adulto e páginas sugestivas; infraestrutura russa.",
        ],
        .japanese: [
            "cloudflare": "最速のパブリックDNS。コンテンツフィルタリングなし。クエリログは24時間後に削除。",
            "google": "Googleのグローバルanycast。フィルタリングなし、Google標準のプライバシーポリシー。",
            "adguard-unfiltered": "AdGuardのプレーンリゾルバ：ブロックなし、プライバシー重視、DNSログなし。",
            "yandex": "ロシア・CIS地域で最速。フィルタリングなし。",
            "dns-watch": "ドイツ製、プライバシー重視、フィルタ・ログなし。",
            "verisign": "安定した米国インフラ。フィルタリングなし。",
            "level3": "古典的なベテランリゾルバ。フィルタリングなし。",
            "quad9": "マルウェア、フィッシング、ボットネットC2ドメインをブロック。スイスの非営利。IPログなし。",
            "cloudflare-malware": "Cloudflareの速度＋マルウェア・フィッシングドメインのブロックリスト。",
            "dns0-zero": "EUの非営利。マルウェア・フィッシングドメインをブロック。",
            "opendns": "Ciscoのリゾルバ。フィッシングと個人情報盗難サイトをブロック。",
            "comodo": "悪性・フィッシングドメインをブロック。",
            "adguard": "広告、トラッカー、アクセス解析、マルウェアドメインをブロック。一部サイトで問題が出る場合あり。",
            "cloudflare-family": "アダルト（18禁）コンテンツとマルウェアドメインをブロック。",
            "adguard-family": "アダルト、広告、トラッカー、マルウェアをブロック。セーフサーチを強制。",
            "cleanbrowsing-family": "厳格モード：アダルト、マルウェア、フィッシングをブロック。Google/Bing/Yandexでセーフサーチ強制。",
            "cleanbrowsing-adult": "アダルトサイト（18禁）のみブロック。それ以外は許可。",
            "opendns-familyshield": "設定済み：アダルトとフィッシングをブロック。設定不要。",
            "yandex-family": "アダルトコンテンツと不適切なページをブロック。ロシアのインフラ。",
        ],
        .chinese: [
            "cloudflare": "最快的公共解析器。无内容过滤；查询日志24小时后删除。",
            "google": "谷歌全球任播。无内容过滤，标准谷歌隐私政策。",
            "adguard-unfiltered": "AdGuard 普通解析器：完全无拦截，隐私优先，不记录 DNS 日志。",
            "yandex": "俄罗斯/独联体地区最快。不过滤。",
            "dns-watch": "德国服务，注重隐私，无过滤、无日志。",
            "verisign": "稳定的美国基础设施。不过滤。",
            "level3": "经典老牌解析器。不过滤。",
            "quad9": "拦截恶意软件、钓鱼及僵尸网络控制域名。瑞士非营利；不记录 IP。",
            "cloudflare-malware": "Cloudflare 速度加恶意与钓鱼域名拦截列表。",
            "dns0-zero": "欧盟非营利组织。拦截恶意与钓鱼域名。",
            "opendns": "思科解析器。拦截钓鱼与身份盗取网站。",
            "comodo": "拦截恶意与钓鱼域名。",
            "adguard": "拦截广告、追踪器、统计信标与恶意域名。个别网站可能异常（反广告拦截墙）。",
            "cloudflare-family": "拦截成人（18+）内容与恶意域名。",
            "adguard-family": "拦截成人内容、广告、追踪器与恶意软件；强制安全搜索。",
            "cleanbrowsing-family": "严格模式：拦截成人内容、恶意与钓鱼；在 Google/Bing/Yandex 强制安全搜索。",
            "cleanbrowsing-adult": "仅拦截成人（18+）网站；其余全部放行。",
            "opendns-familyshield": "预配置：拦截成人与钓鱼内容。无需设置。",
            "yandex-family": "拦截成人与不良页面；俄罗斯基础设施。",
        ],
        .korean: [
            "cloudflare": "가장 빠른 공용 리졸버. 콘텐츠 필터링 없음; 조회 로그 24시간 후 삭제.",
            "google": "구글 글로벌 애니캐스트. 콘텐츠 필터링 없음, 구글 표준 개인정보 정책.",
            "adguard-unfiltered": "AdGuard 기본 리졸버: 차단 없음, 프라이버시 우선, DNS 로그 없음.",
            "yandex": "러시아/CIS 지역에서 가장 빠름. 필터링 없음.",
            "dns-watch": "독일산, 프라이버시 친화적, 필터·로그 없음.",
            "verisign": "안정적인 미국 인프라. 필터링 없음.",
            "level3": "클래식 베테랑 리졸버. 필터링 없음.",
            "quad9": "악성코드, 피싱, 봇넷 제어 도메인 차단. 스위스 비영리; IP 로그 없음.",
            "cloudflare-malware": "Cloudflare 속도 + 악성·피싱 도메인 차단 목록.",
            "dns0-zero": "EU 비영리. 악성·피싱 도메인 차단.",
            "opendns": "시스코 리졸버. 피싱 및 개인정보 도용 사이트 차단.",
            "comodo": "악성·피싱 도메인 차단.",
            "adguard": "광고, 추적기, 분석 비컨, 악성 도메인 차단. 일부 사이트가 깨질 수 있음(안티 애드블록).",
            "cloudflare-family": "성인(19+) 콘텐츠 및 악성 도메인 차단.",
            "adguard-family": "성인 콘텐츠, 광고, 추적기, 악성코드 차단; 세이프서치 강제.",
            "cleanbrowsing-family": "엄격 모드: 성인 콘텐츠, 악성코드, 피싱 차단; Google/Bing/Yandex 세이프서치 강제.",
            "cleanbrowsing-adult": "성인(19+) 사이트만 차단; 나머지는 모두 허용.",
            "opendns-familyshield": "사전 구성: 성인 콘텐츠 및 피싱 차단. 설정 불필요.",
            "yandex-family": "성인 콘텐츠 및 선정적 페이지 차단; 러시아 인프라.",
        ],
        .arabic: [
            "cloudflare": "أسرع محلّل DNS عام. بدون تصفية محتوى؛ تُحذف سجلات الاستعلام بعد 24 ساعة.",
            "google": "أنكاست عالمي من جوجل. بدون تصفية محتوى، سياسة خصوصية جوجل القياسية.",
            "adguard-unfiltered": "محلّل AdGuard البسيط: بدون أي حجب، الخصوصية أولًا، بدون سجلات DNS.",
            "yandex": "الأسرع في روسيا/رابطة الدول المستقلة. بدون تصفية.",
            "dns-watch": "ألماني، صديق للخصوصية، بدون فلاتر أو سجلات.",
            "verisign": "بنية تحتية أمريكية مستقرة. بدون تصفية.",
            "level3": "محلّل قديم وكلاسيكي. بدون تصفية.",
            "quad9": "يحجب البرمجيات الخبيثة والتصيّد ونطاقات التحكم بالبوتنت. منظمة سويسرية غير ربحية؛ بدون تسجيل عناوين IP.",
            "cloudflare-malware": "سرعة Cloudflare مع قائمة حجب لنطاقات البرمجيات الخبيثة والتصيّد.",
            "dns0-zero": "منظمة أوروبية غير ربحية. تحجب نطاقات البرمجيات الخبيثة والتصيّد.",
            "opendns": "محلّل Cisco. يحجب التصيّد وسرقة الهوية.",
            "comodo": "يحجب النطاقات الخبيثة والتصيّدية.",
            "adguard": "يحجب الإعلانات والمتتبعات وتحليلات الاستخدام والنطاقات الخبيثة. بعض المواقع قد تتعطل (حواجز منع مانع الإعلانات).",
            "cloudflare-family": "يحجب محتوى البالغين (+18) والنطاقات الخبيثة.",
            "adguard-family": "يحجب محتوى البالغين والإعلانات والمتتبعات والبرمجيات الخبيثة؛ يفرض البحث الآمن.",
            "cleanbrowsing-family": "وضع صارم: يحجب محتوى البالغين والخبيث والتصيّد؛ يفرض البحث الآمن في Google/Bing/Yandex.",
            "cleanbrowsing-adult": "يحجب مواقع البالغين (+18) فقط؛ كل شيء آخر مسموح.",
            "opendns-familyshield": "مهيأ مسبقًا: يحجب محتوى البالغين والتصيّد. لا يحتاج إعدادًا.",
            "yandex-family": "يحجب محتوى البالغين والصفحات المثيرة؛ بنية تحتية روسية.",
        ],
        .hindi: [
            "cloudflare": "सबसे तेज़ सार्वजनिक रिज़ॉल्वर। कोई कंटेंट फ़िल्टरिंग नहीं; क्वेरी लॉग 24 घंटे बाद मिट जाते हैं।",
            "google": "Google का ग्लोबल एनीकास्ट। कोई कंटेंट फ़िल्टरिंग नहीं, Google की मानक गोपनीयता नीति।",
            "adguard-unfiltered": "AdGuard का सादा रिज़ॉल्वर: कोई ब्लॉकिंग नहीं, गोपनीयता सर्वोपरि, कोई DNS लॉग नहीं।",
            "yandex": "रूस/CIS क्षेत्र में सबसे तेज़। कोई फ़िल्टरिंग नहीं।",
            "dns-watch": "जर्मन, गोपनीयता-मित्र, बिना फ़िल्टर और लॉग।",
            "verisign": "स्थिर US इंफ़्रास्ट्रक्चर। कोई फ़िल्टरिंग नहीं।",
            "level3": "क्लासिक अनुभवी रिज़ॉल्वर। कोई फ़िल्टरिंग नहीं।",
            "quad9": "मैलवेयर, फ़िशिंग और बॉटनेट कंट्रोल डोमेन ब्लॉक करता है। स्विस गैर-लाभकारी; IP लॉगिंग नहीं।",
            "cloudflare-malware": "Cloudflare की गति साथ मैलवेयर और फ़िशिंग डोमेन ब्लॉकलिस्ट।",
            "dns0-zero": "EU गैर-लाभकारी। मैलवेयर और फ़िशिंग डोमेन ब्लॉक करता है।",
            "opendns": "Cisco का रिज़ॉल्वर। फ़िशिंग और पहचान चोरी साइटें ब्लॉक करता है।",
            "comodo": "दुर्भावनापूर्ण और फ़िशिंग डोमेन ब्लॉक करता है।",
            "adguard": "विज्ञापन, ट्रैकर, एनालिटिक्स और मैलवेयर डोमेन ब्लॉक करता है। कुछ साइटें टूट सकती हैं (एंटी-ऐडब्लॉक)।",
            "cloudflare-family": "वयस्क (18+) कंटेंट और मैलवेयर डोमेन ब्लॉक करता है।",
            "adguard-family": "वयस्क कंटेंट, विज्ञापन, ट्रैकर और मैलवेयर ब्लॉक करता है; सुरक्षित खोज लागू करता है।",
            "cleanbrowsing-family": "सख्त मोड: वयस्क कंटेंट, मैलवेयर और फ़िशिंग ब्लॉक; Google/Bing/Yandex पर सुरक्षित खोज लागू।",
            "cleanbrowsing-adult": "केवल वयस्क (18+) साइटें ब्लॉक; बाकी सब अनुमति।",
            "opendns-familyshield": "पहले से कॉन्फ़िगर: वयस्क कंटेंट और फ़िशिंग ब्लॉक। कुछ सेट करने की ज़रूरत नहीं।",
            "yandex-family": "वयस्क कंटेंट और संदिग्ध पेज ब्लॉक करता है; रूसी इंफ़्रास्ट्रक्चर।",
        ],
        .thai: [
            "cloudflare": "รีซอลเวอร์สาธารณะที่เร็วที่สุด ไม่กรองเนื้อหา; ลบบันทึกคิวรีหลัง 24 ชม.",
            "google": "แอนีแคสต์ทั่วโลกจาก Google ไม่กรองเนื้อหา ตามนโยบายความเป็นส่วนตัวมาตรฐานของ Google",
            "adguard-unfiltered": "รีซอลเวอร์พื้นฐานของ AdGuard: ไม่บล็อกเลย เน้นความเป็นส่วนตัว ไม่เก็บบันทึก DNS",
            "yandex": "เร็วที่สุดในรัสเซีย/CIS ไม่กรองเนื้อหา",
            "dns-watch": "เซิร์ฟเวอร์เยอรมัน เป็นมิตรกับความเป็นส่วนตัว ไม่กรองและไม่เก็บบันทึก",
            "verisign": "โครงสร้างพื้นฐานสหรัฐฯ ที่เสถียร ไม่กรองเนื้อหา",
            "level3": "รีซอลเวอร์คลาสสิกยอดเก่า ไม่กรองเนื้อหา",
            "quad9": "บล็อกมัลแวร์ ฟิชชิง และโดเมนควบคุมบ็อตเน็ต องค์กรไม่แสวงผลกำไรสวิส ไม่บันทึก IP",
            "cloudflare-malware": "ความเร็วของ Cloudflare พร้อมบล็อกลิสต์โดเมนมัลแวร์และฟิชชิง",
            "dns0-zero": "องค์กรไม่แสวงผลกำไรแห่ง EU บล็อกโดเมนมัลแวร์และฟิชชิง",
            "opendns": "รีซอลเวอร์ของ Cisco บล็อกฟิชชิงและการขโมยข้อมูลส่วนตัว",
            "comodo": "บล็อกโดเมนที่เป็นอันตรายและฟิชชิง",
            "adguard": "บล็อกโฆษณา แทรกเกอร์ สคริปต์วิเคราะห์ และโดเมนมัลแวร์ บางเว็บอาจพัง (กำแพงกันอาดบล็อก)",
            "cloudflare-family": "บล็อกเนื้อหา 18+ และโดเมนมัลแวร์",
            "adguard-family": "บล็อกเนื้อหา 18+ โฆษณา แทรกเกอร์ และมัลแวร์; บังคับค้นหาแบบปลอดภัย",
            "cleanbrowsing-family": "โหมดเข้มงวด: บล็อกเนื้อหา 18+ มัลแวร์ ฟิชชิง; บังคับ Safe Search บน Google/Bing/Yandex",
            "cleanbrowsing-adult": "บล็อกเฉพาะเว็บ 18+ ที่เหลืออนุญาตทั้งหมด",
            "opendns-familyshield": "ตั้งค่ามาแล้ว: บล็อกเนื้อหา 18+ และฟิชชิง ไม่ต้องตั้งค่าเพิ่ม",
            "yandex-family": "บล็อกเนื้อหา 18+ และหน้าที่ไม่เหมาะสม โครงสร้างพื้นฐานรัสเซีย",
        ],
        .turkish: [
            "cloudflare": "En hızlı genel DNS çözümleyicisi. İçerik filtreleme yok; sorgu kayıtları 24 saat sonra silinir.",
            "google": "Google küresel anycast. İçerik filtreleme yok, standart Google gizlilik politikası.",
            "adguard-unfiltered": "AdGuard sade çözümleyici: hiç engelleme yok, gizlilik önce, DNS kaydı yok.",
            "yandex": "Rusya/BDT bölgesinde en hızlısı. Filtreleme yok.",
            "dns-watch": "Alman, gizlilik dostu, filtresiz ve kayıtsız.",
            "verisign": "Stabil ABD altyapısı. Filtreleme yok.",
            "level3": "Klasik eski çözümleyici. Filtreleme yok.",
            "quad9": "Zararlı yazılım, oltalama ve botnet kontrol alan adlarını engeller. İsviçre kâr amacı gütmeyen; IP kaydı yok.",
            "cloudflare-malware": "Cloudflare hızı artı zararlı yazılım ve oltalama alan adı engelleme listesi.",
            "dns0-zero": "AB merkezli kâr amacı gütmeyen. Zararlı yazılım ve oltalama alan adlarını engeller.",
            "opendns": "Cisco çözümleyicisi. Oltalama ve kimlik hırsızlığı sitelerini engeller.",
            "comodo": "Zararlı ve oltalama alan adlarını engeller.",
            "adguard": "Reklamları, izleyicileri, analiz kodlarını ve zararlı alan adlarını engeller. Bazı siteler bozulabilir (reklam engelleme duvarları).",
            "cloudflare-family": "Yetişkin (+18) içerik ve zararlı alan adlarını engeller.",
            "adguard-family": "Yetişkin içeriği, reklamları, izleyicileri ve zararlıları engeller; güvenli aramayı zorunlu kılar.",
            "cleanbrowsing-family": "Sıkı mod: yetişkin içerik, zararlı yazılım ve oltalamayı engeller; Google/Bing/Yandex'te güvenli arama.",
            "cleanbrowsing-adult": "Yalnızca yetişkin (+18) siteleri engeller; gerisinin izinli.",
            "opendns-familyshield": "Ön ayarlı: yetişkin içerik ve oltalamayı engeller. Ayar gerekmez.",
            "yandex-family": "Yetişkin içerik ve müstehcen sayfaları engeller; Rus altyapısı.",
        ],
        .polish: [
            "cloudflare": "Najszybszy publiczny resolver. Bez filtrowania treści; logi zapytań usuwane po 24h.",
            "google": "Globalny anycast Google. Bez filtrowania treści, standardowa polityka prywatności Google.",
            "adguard-unfiltered": "Zwykły resolver AdGuard: bez blokowania, prywatność przede wszystkim, bez logów DNS.",
            "yandex": "Najszybszy w Rosji/ONS. Bez filtrowania.",
            "dns-watch": "Niemiecki, przyjazny prywatności, bez filtrów i logów.",
            "verisign": "Stabilna infrastruktura USA. Bez filtrowania.",
            "level3": "Klasyczny weteran wśród resolverów. Bez filtrowania.",
            "quad9": "Blokuje malware, phishing i domeny kontrolne botnetów. Szwajcarska organizacja non-profit; bez logowania IP.",
            "cloudflare-malware": "Szybkość Cloudflare plus lista blokowania domen malware i phishingu.",
            "dns0-zero": "Unijna organizacja non-profit. Blokuje domeny malware i phishingu.",
            "opendns": "Resolver Cisco. Blokuje phishing i kradzież tożsamości.",
            "comodo": "Blokuje złośliwe domeny i phishing.",
            "adguard": "Blokuje reklamy, trackery, analitykę i domeny malware. Niektóre strony mogą się psuć (ściany anti-adblock).",
            "cloudflare-family": "Blokuje treści dla dorosłych (18+) i domeny malware.",
            "adguard-family": "Blokuje treści dla dorosłych, reklamy, trackery i malware; wymusza bezpieczne wyszukiwanie.",
            "cleanbrowsing-family": "Tryb rygorystyczny: blokuje treści dla dorosłych, malware i phishing; wymusza Safe Search w Google/Bing/Yandex.",
            "cleanbrowsing-adult": "Blokuje tylko strony dla dorosłych (18+); cała reszta dozwolona.",
            "opendns-familyshield": "Skonfigurowany z góry: blokuje treści dla dorosłych i phishing. Niczego nie trzeba ustawiać.",
            "yandex-family": "Blokuje treści dla dorosłych i wątpliwe strony; rosyjska infrastruktura.",
        ],
        .dutch: [
            "cloudflare": "De snelste publieke resolver. Geen inhoudsfiltering; querylogs worden na 24 uur gewist.",
            "google": "Google's wereldwijde anycast. Geen inhoudsfiltering, standaard Google-privacybeleid.",
            "adguard-unfiltered": "AdGuard's gewone resolver: geen blokkering, privacy voorop, geen DNS-logs.",
            "yandex": "Het snelst in Rusland/GOS. Geen filtering.",
            "dns-watch": "Duits, privacyvriendelijk, zonder filters of logs.",
            "verisign": "Stabiele VS-infrastructuur. Geen filtering.",
            "level3": "Klassieke veteraan onder de resolvers. Geen filtering.",
            "quad9": "Blokkeert malware, phishing en botnet-commandodomeinen. Zwitsers non-profit; geen IP-logging.",
            "cloudflare-malware": "Cloudflare-snelheid plus een blokkeerlijst van malware- en phishingdomeinen.",
            "dns0-zero": "EU non-profit. Blokkeert malware- en phishingdomeinen.",
            "opendns": "Resolver van Cisco. Blokkeert phishing en identiteitsdiefstal.",
            "comodo": "Blokkeert kwaadaardige en phishingdomeinen.",
            "adguard": "Blokkeert advertenties, trackers, analytics en malwaredomeinen. Sommige sites kunnen breken (anti-adblockmuren).",
            "cloudflare-family": "Blokkeert volwassen (18+) inhoud en malwaredomeinen.",
            "adguard-family": "Blokkeert volwassen inhoud, advertenties, trackers en malware; forceert veilig zoeken.",
            "cleanbrowsing-family": "Strikte modus: blokkeert volwassen inhoud, malware en phishing; forceert veilig zoeken in Google/Bing/Yandex.",
            "cleanbrowsing-adult": "Blokkeert alleen volwassen (18+) sites; alle rest is toegestaan.",
            "opendns-familyshield": "Vooraf ingesteld: blokkeert volwassen inhoud en phishing. Niets in te stellen.",
            "yandex-family": "Blokkeert volwassen inhoud en dubieuze pagina's; Russische infrastructuur.",
        ],
        .vietnamese: [
            "cloudflare": "Bộ phân giải công khai nhanh nhất. Không lọc nội dung; nhật ký truy vấn bị xóa sau 24 giờ.",
            "google": "Anycast toàn cầu của Google. Không lọc nội dung, chính sách quyền riêng tư chuẩn của Google.",
            "adguard-unfiltered": "Bộ phân giải giản đơn của AdGuard: không chặn gì, ưu tiên riêng tư, không lưu nhật ký DNS.",
            "yandex": "Nhanh nhất ở Nga/CIS. Không lọc.",
            "dns-watch": "Đức, thân thiện quyền riêng tư, không lọc, không nhật ký.",
            "verisign": "Hạ tầng Mỹ ổn định. Không lọc.",
            "level3": "Bộ phân giải lâu đời kinh điển. Không lọc.",
            "quad9": "Chặn mã độc, lừa đảo và miền điều khiển botnet. Tổ chức phi lợi nhuận Thụy Sĩ; không ghi log IP.",
            "cloudflare-malware": "Tốc độ Cloudflare kèm danh sách chặn miền mã độc và lừa đảo.",
            "dns0-zero": "Tổ chức phi lợi nhuận EU. Chặn miền mã độc và lừa đảo.",
            "opendns": "Bộ phân giải của Cisco. Chặn lừa đảo và đánh cắp danh tính.",
            "comodo": "Chặn miền độc hại và lừa đảo.",
            "adguard": "Chặn quảng cáo, trình theo dõi, phân tích và miền mã độc. Một số trang có thể hỏng (tường chống adblock).",
            "cloudflare-family": "Chặn nội dung người lớn (18+) và miền mã độc.",
            "adguard-family": "Chặn nội dung người lớn, quảng cáo, theo dõi và mã độc; buộc tìm kiếm an toàn.",
            "cleanbrowsing-family": "Chế độ nghiêm: chặn nội dung người lớn, mã độc, lừa đảo; buộc tìm kiếm an toàn trên Google/Bing/Yandex.",
            "cleanbrowsing-adult": "Chỉ chặn trang người lớn (18+); còn lại đều được phép.",
            "opendns-familyshield": "Cài sẵn: chặn nội dung người lớn và lừa đảo. Không cần cấu hình.",
            "yandex-family": "Chặn nội dung người lớn và trang khiêu khích; hạ tầng Nga.",
        ],
    ]
}
